const state={server:'',user:'',pass:'',proxy:false,catalog:{live:[],movie:[],series:[]},categories:{live:[],movie:[],series:[]},limit:{live:24,movie:24,series:24},current:null};
let hls=null;const $=id=>document.getElementById(id);const favorites=new Set(JSON.parse(localStorage.getItem('rw-favorites-v2')||'[]'));
const normalizeServer=v=>v.trim().replace(/\/+$/,'');
function apiUrl(action,params={}){const base=state.proxy?'proxy.php':`${state.server}/player_api.php`;const q=new URLSearchParams({...(state.proxy?{server:state.server}:{}),username:state.user,password:state.pass,...(action?{action}:{}),...params});return `${base}?${q}`;}
async function request(action,params={}){const r=await fetch(apiUrl(action,params),{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Servidor respondeu ${r.status}`);const data=await r.json();if(data?.user_info?.auth===0)throw new Error('Usuário ou senha inválidos.');return data;}
function streamUrl(item){if(item.kind==='live')return `${state.server}/live/${encodeURIComponent(state.user)}/${encodeURIComponent(state.pass)}/${item.stream_id}.m3u8`;if(item.kind==='movie')return `${state.server}/movie/${encodeURIComponent(state.user)}/${encodeURIComponent(state.pass)}/${item.stream_id}.${item.container_extension||'mp4'}`;return item.url||'';}
function mapItem(raw,kind){return{id:`${kind}-${raw.stream_id||raw.series_id}`,kind,title:raw.name||'Sem título',categoryId:String(raw.category_id||''),image:raw.stream_icon||raw.cover||'',stream_id:raw.stream_id,series_id:raw.series_id,container_extension:raw.container_extension,rating:raw.rating||'',description:raw.plot||raw.epg_channel_id||''};}
async function login(e){e.preventDefault();const status=$('loginStatus');status.className='login-status';status.textContent='Conectando ao servidor...';state.server=normalizeServer($('serverUrl').value);state.user=$('username').value.trim();state.pass=$('password').value;state.proxy=$('useProxy').checked;if($('rememberServer').checked)localStorage.setItem('rw-server',state.server);else localStorage.removeItem('rw-server');try{const account=await request('');if(!account.user_info||String(account.user_info.auth)!=='1')throw new Error('Acesso não autorizado.');status.textContent='Acesso confirmado. Carregando catálogo...';status.classList.add('ok');await loadCatalog();$('accountInfo').textContent=`Conectado como ${state.user}${account.user_info.exp_date?` • validade: ${new Date(Number(account.user_info.exp_date)*1000).toLocaleDateString('pt-BR')}`:''}`;$('loginScreen').hidden=true;$('app').hidden=false;renderAll();}catch(err){status.textContent=`Não foi possível entrar: ${err.message} Verifique DNS, credenciais, HTTPS e CORS.`;}}
async function loadCatalog(){const [lc,mc,sc,l,m,s]=await Promise.all([request('get_live_categories'),request('get_vod_categories'),request('get_series_categories'),request('get_live_streams'),request('get_vod_streams'),request('get_series')]);state.categories.live=Array.isArray(lc)?lc:[];state.categories.movie=Array.isArray(mc)?mc:[];state.categories.series=Array.isArray(sc)?sc:[];state.catalog.live=(Array.isArray(l)?l:[]).map(x=>mapItem(x,'live'));state.catalog.movie=(Array.isArray(m)?m:[]).map(x=>mapItem(x,'movie'));state.catalog.series=(Array.isArray(s)?s:[]).map(x=>mapItem(x,'series'));fillCategories();}
function fillCategories(){[['live','liveCategory'],['movie','movieCategory'],['series','seriesCategory']].forEach(([kind,id])=>{const sel=$(id);sel.innerHTML='<option value="">Todas as categorias</option>'+state.categories[kind].map(c=>`<option value="${escapeHtml(String(c.category_id))}">${escapeHtml(c.category_name)}</option>`).join('');});}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function card(item){const fav=favorites.has(item.id);return `<article class="card" data-title="${escapeHtml(item.title.toLowerCase())}"><div class="card-art">${item.image?`<img class="card-image" loading="lazy" referrerpolicy="no-referrer" src="${escapeHtml(item.image)}" alt="" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'card-placeholder',textContent:'${escapeHtml(item.title).replace(/'/g,'\\\'')}' }))">`:`<div class="card-placeholder">${escapeHtml(item.title)}</div>`}</div><div class="card-body"><h3 class="card-title">${escapeHtml(item.title)}</h3><div class="card-meta">${item.kind==='live'?'<span class="status-dot"></span> AO VIVO':item.kind==='movie'?'FILME':'SÉRIE'} ${item.rating?`• ${escapeHtml(item.rating)}`:''}</div><div class="card-actions">${item.kind!=='series'?`<button class="mini-btn play" data-play="${item.id}">▶</button>`:''}<button class="mini-btn ${fav?'active':''}" data-fav="${item.id}">${fav?'✓':'+'}</button></div></div></article>`;}
function selected(kind){const id=kind==='live'?'liveCategory':kind==='movie'?'movieCategory':'seriesCategory';const cat=$(id).value;const term=$('searchInput').value.trim().toLowerCase();return state.catalog[kind].filter(x=>(!cat||x.categoryId===cat)&&(!term||x.title.toLowerCase().includes(term)));}
function render(kind){const grid=kind==='live'?$('liveGrid'):kind==='movie'?$('moviesGrid'):$('seriesGrid');grid.innerHTML=selected(kind).slice(0,state.limit[kind]).map(card).join('')||'<div class="error-box">Nenhum conteúdo encontrado nesta categoria.</div>';}
function renderFavorites(){const all=[...state.catalog.live,...state.catalog.movie,...state.catalog.series].filter(x=>favorites.has(x.id));$('favoritesGrid').innerHTML=all.map(card).join('');$('emptyList').style.display=all.length?'none':'grid';}
function renderAll(){render('live');render('movie');render('series');renderFavorites();}
async function playItem(id){const item=[...state.catalog.live,...state.catalog.movie].find(x=>x.id===id);if(!item)return;state.current=item;$('playerTitle').textContent=item.title;$('playerDescription').textContent=item.description||'';$('playerBadge').textContent=item.kind==='live'?'AO VIVO':'FILME';$('playerModal').classList.add('open');document.body.style.overflow='hidden';const url=streamUrl(item);$('videoStatus').style.display='grid';$('videoStatus').textContent='Preparando transmissão...';if(hls){hls.destroy();hls=null;}$('videoPlayer').removeAttribute('src');if(item.kind==='live'&&window.Hls&&Hls.isSupported()){hls=new Hls();hls.loadSource(url);hls.attachMedia($('videoPlayer'));hls.on(Hls.Events.MANIFEST_PARSED,()=>{$('videoStatus').style.display='none';$('videoPlayer').play().catch(()=>{});});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)$('videoStatus').textContent='Falha ao carregar. O servidor pode bloquear reprodução no navegador.';});}else{$('videoPlayer').src=url;$('videoPlayer').onloadedmetadata=()=>{$('videoStatus').style.display='none';$('videoPlayer').play().catch(()=>{});};$('videoPlayer').onerror=()=>{$('videoStatus').textContent='Formato não suportado ou acesso bloqueado pelo servidor.';};}}
function closePlayer(){$('playerModal').classList.remove('open');$('videoPlayer').pause();$('videoPlayer').removeAttribute('src');if(hls){hls.destroy();hls=null;}document.body.style.overflow='';}
function logout(){closePlayer();state.pass='';state.user='';state.catalog={live:[],movie:[],series:[]};$('app').hidden=true;$('loginScreen').hidden=false;$('password').value='';$('loginStatus').textContent='Sessão encerrada.';}
$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);$('serverUrl').value=localStorage.getItem('rw-server')||'';$('rememberServer').checked=!!localStorage.getItem('rw-server');
document.addEventListener('click',e=>{const p=e.target.closest('[data-play]'),f=e.target.closest('[data-fav]'),m=e.target.closest('[data-kind]');if(p)playItem(p.dataset.play);if(f){favorites.has(f.dataset.fav)?favorites.delete(f.dataset.fav):favorites.add(f.dataset.fav);localStorage.setItem('rw-favorites-v2',JSON.stringify([...favorites]));renderAll();}if(m){state.limit[m.dataset.kind]+=24;render(m.dataset.kind);}if(e.target.closest('[data-close-modal]'))closePlayer();});
['liveCategory','movieCategory','seriesCategory'].forEach(id=>$(id).addEventListener('change',renderAll));$('searchToggle').addEventListener('click',()=>{$('searchPanel').classList.add('open');$('searchInput').focus();});$('closeSearch').addEventListener('click',()=>{$('searchPanel').classList.remove('open');$('searchInput').value='';renderAll();});$('searchInput').addEventListener('input',renderAll);window.addEventListener('keydown',e=>{if(e.key==='Escape')closePlayer();});
